### PR TITLE
Reformat README for readability, see #19

### PR DESCRIPTION
**Pull request by franz-josef-kaiser**
* Changed the `README` format from _none_ to _MarkDown_
* Added brief _Homebrew_ installation instructions
* Added Issue/Reporting guideline

Preview [in this fork](https://github.com/franz-josef-kaiser/fuse-ext2).

Thanks for you work here, @alperakcan !

Oh, and sorry for directly sending this to `master`, I figured it would be easier as this is a non-breaking change and does not need a merge.

### CODE REVIEW

**Comment by Cabalist** [comment]
The build instructions for Homebrew do not appear to work as written.  

1) m4 is ```homebrew/dupes/m4```
2) ```CFLAGS="-idirafter/$(brew --prefix e2fsprogs)/include -idirafter/usr/local/include/osxfuse" LDFLAGS="-L$(brew --prefix e2fsprogs)/lib" ./configure``` fails saying their is no file called ```configure``` because you haven't run autogen.sh yet
3) After running autogen.sh I get the error ```configure: error: Can't find libfuse, please install it```  which might be an issue with my environment but I do have OSXFuse installed from their package.


I hope this helps. :)

**Comment by franz-josef-kaiser** [comment]
> I hope this helps. :)

Absolutely! Thanks a bunch. Will update according to your test (after I have confirmed it to double check that).

**Comment by kuantico** [comment]
I have exactly the same problem that Cabalist, error: Can't find libfuse, please install it, I am on "El Capitan"

**Comment by kuantico** [comment]
finally, the reason for "configure: error: Can't find libfuse, please install it" is the path, the path is wrong.
replace the following command:
CFLAGS="-idirafter/$(brew --prefix e2fsprogs)/include -idirafter/usr/local/include/osxfuse" LDFLAGS="-L$(brew --prefix e2fsprogs)/lib" ./configure

with this one:

CFLAGS="-idirafter/usr/local/Cellar/e2fsprogs/1.42.13/include -idirafter/usr/local/include/osxfuse/" LDFLAGS="-L/usr/local/lib -L/usr/local/Cellar/e2fsprogs/1.42.13/lib" ./configure

you can check the path with: locate e2fsprogs
if do not appear try:
sudo /usr/libexec/locate.updatedb

and then again:
locate e2fsprogs

then you will find an error again when you try the sudo make install command

you will have to reboot in recovery mode holding Command + R and executing csrutil disable; reboot command

then execute sudo make install command

and finish.

but at the end i can not get the access to the disk I wish. the partitions appear mounted but I can not see any files, something is not working like it was in Yosemite. 

reference of the solution is in next link:
https://github.com/alperakcan/fuse-ext2/issues/10
http://osxdaily.com/2015/10/05/disable-rootless-system-integrity-protection-mac-os-x/

**Comment by kuantico** [comment]
this is the problem that I have now:

(that from /var/log/fuse-ext2_util.log)

2016-02-04 09:32:11: fuse-ext2 script invoked with command line "/System/Library/Filesystems/fuse-ext2.fs/fuse-ext2.util" "-m" "-o" "nodev" "-o" "noowners" "-o" "nosuid" "/dev/disk2s1" "/Volumes/Untitled 25"
2016-02-04 09:32:11: Invoking user: root
2016-02-04 09:32:11: [Mount] Entering function Mount...
2016-02-04 09:32:11: [Mount] Processing argument "/dev/disk2s1"
2016-02-04 09:32:11: [Mount] Processing argument "/Volumes/Untitled 25"
2016-02-04 09:32:11: [Mount] Got plain device "/dev/disk2s1"
2016-02-04 09:32:11: [Mount] Got raw device "/dev/rdisk2s1"
2016-02-04 09:32:11: [Mount] Invoking:
2016-02-04 09:32:11: [Mount]   "/usr/local/bin/fuse-ext2.wait" "/Volumes/Untitled 25" "5" "/usr/local/bin/fuse-ext2" "/dev/disk2s1" "/Volumes/Untitled 25" "-oauto_xattr,defer_permissions,local"
2016-02-04 09:32:16: [Mount] /usr/local/bin/fuse-ext2.wait returned with retval: 0
2016-02-04 09:32:16: [Mount] Output from mount operation: Mounting /dev/disk2s1 Read-Only.
Use 'force' or 'rw+' options to enable Read-Write mode
mount_osxfusefs: 'default_permissions' can't be used with 'defer_permissions'
Did not receive a signal within 5.000000 seconds. Exiting...
2016-02-04 09:32:16: [Mount] Executing "/usr/local/bin/fuse-ext2.daemon"
2016-02-04 09:32:16: [Mount] Exiting function mount...
2016-02-04 09:44:07: fuse-ext2 script invoked with command line "/System/Library/Filesystems/fuse-ext2.fs/fuse-ext2.util" "-m" "" "" "" "" "" "" "" ""
2016-02-04 09:44:07: Invoking user: root
2016-02-04 09:44:07: [Mount] Entering function Mount...
2016-02-04 09:44:07: [Mount] Invalid command line! Printing usage and exiting with error...
2016-02-04 09:44:07: [PrintUsage] Entering function PrintUsage...
2016-02-04 09:44:46: fuse-ext2 script invoked with command line "/System/Library/Filesystems/fuse-ext2.fs/fuse-ext2.util" "-m" "-u" "/dev/disk2s1" "" "" "" "" "" ""
2016-02-04 09:44:46: Invoking user: root
2016-02-04 09:44:46: [Mount] Entering function Mount...
2016-02-04 09:44:46: [Mount] Processing argument "-u"
2016-02-04 09:44:46: [Mount] Processing argument "/dev/disk2s1"
2016-02-04 09:44:46: [Mount] Got plain device "/dev/-u"
2016-02-04 09:44:46: [Mount] Got raw device "/dev/-u"
2016-02-04 09:44:46: [Mount] Invoking:
2016-02-04 09:44:46: [Mount]   "/usr/local/bin/fuse-ext2.wait" "/dev/disk2s1" "5" "/usr/local/bin/fuse-ext2" "/dev/-u" "/dev/disk2s1" "-oauto_xattr,defer_permissions,local"
2016-02-04 09:44:46: [Mount] /usr/local/bin/fuse-ext2.wait returned with retval: 253
2016-02-04 09:44:46: [Mount] ERROR: Mounting /dev/-u as /dev/disk2s1 failed! Output: 
2016-02-04 09:44:46: [Mount] Exiting function mount...

any idea?? :-S

**Comment by kuantico** [comment]
change this lines in the sudo vim /System/Library/Filesystems/fuse-ext2.fs/fuse-ext2.util file in the function Mount ():
    #OPTIONS="auto_xattr,defer_permissions"
    OPTIONS="force"

and all works fine.

add  OPTIONS="force,rw+"

if you want to red an write on the disk

reference:
https://www.nukeador.com/30/06/2010/ext3-en-mac-os-x-leer-y-escribir/

**Comment by franz-josef-kaiser** [comment]
@kuantico Can you please format your code? On the bottom of the comment box there's the following link:

> Styling with Markdown is supported

**Comment by tdenta** [comment]
Hello,

I finally found that thread that enabled me to complete successfully some installation steps (thanks to kuantico's posts).

Now, when executing `sudo make install` with SIP disabled, I run into the following error :
`
./fuse-ext2.h:35:10: fatal error: 'ext2fs/ext2fs.h' file not found
`
Any ideas ?

Thanks in advance.

**Comment by kuantico** [comment]
if you execute

`locate ext2fs.h`

i got this in my brew installation:

`/usr/local/Cellar/e2fsprogs/1.42.13/include/ext2fs/ext2fs.h`

**Comment by tdenta** [comment]
Thanks kuantico for that fast answer !
The locate database does not exist on my computer, I just started its creation.

Looking at the location you mentioned, I can find the `ext2fs.h` file right where you expect it.

So maybe I did something wrong ? Has the folder containing all the files of _fuse-ext2_ to be in a specific location for a correct installation (currently it's in my `~/Downloads`) ?

**Comment by kuantico** [comment]
in my case 
first I downloaded https://osxfuse.github.io/

then I follow this instructions:

https://github.com/alperakcan/fuse-ext2?

and after the brew install I move to:

`cd /opt/homebrew-cask/Caskroom/fuse-ext2-master`

**Comment by tdenta** [comment]
I have nothing in `/opt` apart from an `X11` folder.
In my case I installed FUSE (3.2.0), then installed all the brew packages, then dowloaded the _fuse-ext2_ github files from [here](https://github.com/alperakcan/fuse-ext2) (or the official repository, I don't remember).

I unziped the files inside my `~/Downloads`folder, performed the `CFLAG` and `LDFLAG` things inside this folder, then tried to perform the `sudo make` and got the error I mentioned previously.

**Comment by kuantico** [comment]
try just:
brew install e2fsprogs m4 automake autoconf libtool
```
CFLAGS="-idirafter/usr/local/Cellar/e2fsprogs/1.42.13/include -idirafter/usr/local/include/osxfuse/" LDFLAGS="-L/usr/local/lib -L/usr/local/Cellar/e2fsprogs/1.42.13/lib" ./configure
make 
sudo make install
```

watch for the version you have in my case is 1.42.13

**Comment by tdenta** [comment]
I've already installed the packages e2fsprogs, m4, automake, autoconf and libtool.

I made a `brew info e2fsprogs` and it says I have the same version as you (1.42.13).

But, MAKE WORKS NOW ! Have you changed anything in the CFLAGS command ?

**Comment by tdenta** [comment]
Now I have two problems :

- ext2 partitions doesn't mount automatically
- I tried make it manually with `sudo mount -t fuse-ext2 /dev/disk2s2 /Volumes` but I got this error window :

> FUSE-EXT2 could not mount /dev/disk2s2
> at /Volumes because the following problem occurred:

And nothing more !

Any ideas ?

**Comment by kuantico** [comment]
you need to know what is happening. I recommend you to check /var/log/fuse-ext2_util.log file

**Comment by tdenta** [comment]
**I get this everytime I try to mount manually my Raspberry Pi SD Card:**

2016-02-16 02:14:35: fuse-ext2 script invoked with command line "/System/Library/Filesystems/fuse-ext2.fs/Contents/Resources/../../fuse-ext2.util" "-p" "disk2s2" "removable" "re$
2016-02-16 02:14:35: Invoking user: root
2016-02-16 02:14:35: [Probe] Entering function Probe...
2016-02-16 02:14:35: [Probe] Executing "/usr/local/bin/fuse-ext2.probe" "/dev/disk2s2" 2>&1
2016-02-16 02:14:35: [Probe]   Return value: 252
2016-02-16 02:14:35: [Probe]   Volname     :
2016-02-16 02:14:35: [Probe]   Output (PROBE_OUTPUT): ""
2016-02-16 02:14:35: [Probe] PROBE_RETVAL indicated that we can not mount this volume.
2016-02-16 02:14:35: [Probe] returning FSUR_UNRECOGNIZED
2016-02-16 02:14:59: fuse-ext2 script invoked with command line "/System/Library/Filesystems/fuse-ext2.fs/fuse-ext2.util" "-m" "/dev/disk2s2" "/Volumes/Linux" "" "" "" "" "" ""
2016-02-16 02:14:59: Invoking user: root
2016-02-16 02:14:59: [Mount] Entering function Mount...
2016-02-16 02:14:59: [Mount] Processing argument "/dev/disk2s2"
2016-02-16 02:14:59: [Mount] Processing argument "/Volumes/Linux"
2016-02-16 02:14:59: [Mount] Got plain device "/dev/disk2s2"
2016-02-16 02:14:59: [Mount] Got raw device "/dev/rdisk2s2"
2016-02-16 02:14:59: [Mount] Invoking:
2016-02-16 02:14:59: [Mount]   "/usr/local/bin/fuse-ext2.wait" "/Volumes/Linux" "5" "/usr/local/bin/fuse-ext2" "/dev/disk2s2" "/Volumes/Linux" "-oauto_xattr,defer_permissions,lo$
2016-02-16 02:14:59: [Mount] /usr/local/bin/fuse-ext2.wait returned with retval: 252
2016-02-16 02:14:59: [Mount] ERROR: Mounting /dev/disk2s2 as /Volumes/Linux failed! Output:
2016-02-16 02:15:00: [Mount] Exiting function mount...

**Comment by kuantico** [comment]
try to force it:

`sudo /usr/local/bin/fuse-ext2 /dev/nameofthedisk /Volumes/mydisk/ -o force`

**Comment by tdenta** [comment]
I made the changes in the `fuse-ext2.util` that you mentioned 11 days ago, and also tried the command you wrote just above.

Nothing happens this time, no error message but no mounted partition either !

Same error messages in the log file.

**Comment by kuantico** [comment]
is ext3/4, fat or ntfs?

**Comment by tdenta** [comment]
It appears to be ext4. No NTFS.

**Pull request merged**
